import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StateProvider from "../Context/Provider";
import Menu from "./menu";
import toast, { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen bg-gray-100`}>
          <StateProvider>
            <Toaster />
            <Menu />
            {children}
          </StateProvider>
      </body>
    </html>
  );
}
